function orb = pwsdde_coco_2orb(run_id,prob,lab)
%PWSDDE_COCO_2ORB Extract one periodic orbit data structure from the 
% output of COCO
% Input:
%   run_id: string identifier of the continuation run
%   prob: COCO compatible problem structure generated by pwsdde_coco_prob.m
%    -> init_orb: starting periodic orbit data structure
%   lab: index of periodic orbit to extract (default 1)
% Output:
%   orb: data structure of the orbit found during continuation
%    -> sig: solution signature (event list)
%    -> U: state variable vector (M*N*n)
%    -> T: segment lengths (N)
%    -> p: parameter vector
%    -> n: number of degrees of freedom
%    -> M: Chebyshev mesh resolution

if nargin<3
    lab = 1;
end

% necessary indicies
sig = prob.init_orb.sig;    % solution signature
M = prob.init_orb.M;        % Chebyshev mesh resolution
n = prob.init_orb.n;        % number of degrees of freedom
N = length(sig);            % number of smooth segments
L = length(prob.init_orb.p);% number of system parameters (must be equal to length(p_names))
U_idx = 1:M*n*N;            % indicies of the state variable vector
T_idx = M*n*N+(1:N);        % indicies of segment lengths
P_idx = M*n*N+N+(1:L);      % indicies of system parameters

% extract data
chart = coco_read_solution(run_id,lab,'chart');
orb.sig = sig;
orb.U = chart.x(U_idx);
orb.T = chart.x(T_idx);
orb.p = chart.x(P_idx);
orb.n = n;
orb.M = M;

end
